# Generated by Django 3.2.6 on 2021-11-02 09:26

from django.db import migrations, models
import musicapi.models


class Migration(migrations.Migration):

    dependencies = [
        ('musicapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='code',
            field=models.CharField(default=musicapi.models.generic_unique_code, max_length=8, unique=True),
        ),
    ]
